// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKKhM4SPJ8QtZa19IOEdQmvMaHFXYQyUI',
    appId: '1:677849698868:web:0ff1cd313b806d27f1b061',
    messagingSenderId: '677849698868',
    projectId: 'tickeflow-14570',
    authDomain: 'tickeflow-14570.firebaseapp.com',
    storageBucket: 'tickeflow-14570.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh9vdsTaPz023X_zpc4M_q-gDoLPzkE08',
    appId: '1:677849698868:android:9073d851497196aff1b061',
    messagingSenderId: '677849698868',
    projectId: 'tickeflow-14570',
    storageBucket: 'tickeflow-14570.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2seZOugosIigrp8Gv63IJKZ4u4QihME0',
    appId: '1:677849698868:ios:dd26add210fdef50f1b061',
    messagingSenderId: '677849698868',
    projectId: 'tickeflow-14570',
    storageBucket: 'tickeflow-14570.firebasestorage.app',
    iosBundleId: 'com.example.ticketflow',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2seZOugosIigrp8Gv63IJKZ4u4QihME0',
    appId: '1:677849698868:ios:dd26add210fdef50f1b061',
    messagingSenderId: '677849698868',
    projectId: 'tickeflow-14570',
    storageBucket: 'tickeflow-14570.firebasestorage.app',
    iosBundleId: 'com.example.ticketflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKKhM4SPJ8QtZa19IOEdQmvMaHFXYQyUI',
    appId: '1:677849698868:web:3fb78e257fadb92df1b061',
    messagingSenderId: '677849698868',
    projectId: 'tickeflow-14570',
    authDomain: 'tickeflow-14570.firebaseapp.com',
    storageBucket: 'tickeflow-14570.firebasestorage.app',
  );
}
